//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interpreter_Requests
    {
        public int ID { get; set; }
        public string Department { get; set; }
        public string Physician { get; set; }
        public string Program { get; set; }
        public Nullable<System.DateTime> Date_of_Assignment { get; set; }
        public Nullable<System.TimeSpan> Time_of_Assignment { get; set; }
        public string Language { get; set; }
        public string Location { get; set; }
        public string Staff_in_Charge { get; set; }
        public string Contact_Name { get; set; }
        public string Staff_in_Charge_Ph { get; set; }
        public string Contact_Name_Ph { get; set; }
        public string Nature_of_Assignment { get; set; }
        public Nullable<bool> Precaution { get; set; }
        public string Precaution_Note { get; set; }
        public string Gender_Preference { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Patient_Ph { get; set; }
        public string MRN { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> Prebooked { get; set; }
        public Nullable<bool> Immediate { get; set; }
        public Nullable<bool> Emailed { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public Nullable<bool> Reminder { get; set; }
        public Nullable<bool> Going_Directly { get; set; }
        public Nullable<System.DateTime> Date_of_Request { get; set; }
        public Nullable<System.TimeSpan> Time_of_Request { get; set; }
        public string Dispatcher { get; set; }
        public string Volunteer_Name { get; set; }
        public string Agency { get; set; }
        public string Agency_Ph { get; set; }
        public string Agency_Interpeter_Name { get; set; }
        public string Agency_Ref { get; set; }
        public Nullable<bool> Confirmed_MSH { get; set; }
        public Nullable<bool> Filled_Y { get; set; }
        public Nullable<bool> Filled_N { get; set; }
        public Nullable<bool> Filled_LST { get; set; }
        public Nullable<bool> Filled_Cancelled { get; set; }
        public string Reason_for_Cancellation { get; set; }
        public string Comments { get; set; }
    }
}
